Repository H2-AOAO/Server, pull requests merged in 2024-01, with the labels that each got.

#2 [FEATURE] 프로젝트 초기 생성
  server/.gitignore
  server/Dockerfile
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/kr/sesac/aoao/server/ServerApplication.java
  server/src/main/resources/application.properties
  server/src/test/java/kr/sesac/aoao/server/ServerApplicationTests.java
Labels: 🐥 feat

#8 [FEATURE] 이슈, PR 템플릿 수정
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🐬 docs

#10 [FEATURE] 에러처리 구현
  src/main/java/kr/sesac/aoao/server/global/config/SwaggerConfig.java
  src/main/java/kr/sesac/aoao/server/global/controller/dto/response/ExceptionResponse.java
  src/main/java/kr/sesac/aoao/server/global/exception/ApplicationException.java
  src/main/java/kr/sesac/aoao/server/global/exception/ErrorCode.java
  src/main/java/kr/sesac/aoao/server/global/exception/GlobalExceptionHandler.java
  src/main/java/kr/sesac/aoao/server/global/exception/errorcode/GlobalErrorCode.java
  src/main/java/kr/sesac/aoao/server/test/controller/TestController.java
Labels: 🐥 feat

#12 [FEATURE] 유저 관련 API 개발
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/kr/sesac/aoao/server/ServerApplication.java
  src/main/java/kr/sesac/aoao/server/global/config/SecurityConfig.java
  src/main/java/kr/sesac/aoao/server/global/config/SwaggerConfig.java
  src/main/java/kr/sesac/aoao/server/global/controller/dto/response/ExceptionResponse.java
  src/main/java/kr/sesac/aoao/server/global/entity/BaseEntity.java
  src/main/java/kr/sesac/aoao/server/global/exception/ApplicationException.java
  src/main/java/kr/sesac/aoao/server/global/exception/ErrorCode.java
  src/main/java/kr/sesac/aoao/server/global/exception/GlobalExceptionHandler.java
  src/main/java/kr/sesac/aoao/server/global/exception/errorcode/GlobalErrorCode.java
  src/main/java/kr/sesac/aoao/server/test/controller/TestController.java
  src/main/java/kr/sesac/aoao/server/user/controller/UserController.java
  src/main/java/kr/sesac/aoao/server/user/controller/dto/request/SignUpRequest.java
  src/main/java/kr/sesac/aoao/server/user/domain/User.java
  src/main/java/kr/sesac/aoao/server/user/exception/UserErrorCode.java
  src/main/java/kr/sesac/aoao/server/user/repository/Role.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserJpaRepository.java
  src/main/java/kr/sesac/aoao/server/user/service/UserService.java
  src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/kr/sesac/aoao/server/ServerApplicationTests.java
Labels: 🐥 feat

#19 [FEATURE] API 공통 Response 객체 생성
  src/main/java/kr/sesac/aoao/server/global/controller/dto/response/ApplicationResponse.java
  src/main/java/kr/sesac/aoao/server/global/controller/dto/response/ExceptionResponse.java
  src/main/java/kr/sesac/aoao/server/global/exception/GlobalExceptionHandler.java
  src/main/java/kr/sesac/aoao/server/test/controller/TestController.java
Labels: 🐥 feat

#17 [FEATURE] 회원가입, 로그인 API 개발
  build.gradle
  src/main/java/kr/sesac/aoao/server/ServerApplication.java
  src/main/java/kr/sesac/aoao/server/global/config/JpaAuditConfig.java
  src/main/java/kr/sesac/aoao/server/global/config/SecurityConfig.java
  src/main/java/kr/sesac/aoao/server/global/controller/dto/response/ApplicationResponse.java
  src/main/java/kr/sesac/aoao/server/user/SecurityUtil.java
  src/main/java/kr/sesac/aoao/server/user/controller/UserController.java
  src/main/java/kr/sesac/aoao/server/user/controller/dto/request/SignUpRequest.java
  src/main/java/kr/sesac/aoao/server/user/controller/dto/response/JwtTokenResponse.java
  src/main/java/kr/sesac/aoao/server/user/controller/dto/response/SignUpResponse.java
  src/main/java/kr/sesac/aoao/server/user/domain/User.java
  src/main/java/kr/sesac/aoao/server/user/exception/UserErrorCode.java
  src/main/java/kr/sesac/aoao/server/user/jwt/JwtAuthenticationFilter.java
  src/main/java/kr/sesac/aoao/server/user/jwt/JwtTokenProvider.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
  src/main/java/kr/sesac/aoao/server/user/service/CustomUserDetailsService.java
  src/main/java/kr/sesac/aoao/server/user/service/UserService.java
  src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/test/java/kr/sesac/aoao/server/user/controller/UserControllerTest.java
  src/test/java/kr/sesac/aoao/server/user/service/UserServiceImplTest.java
Labels: 🐥 feat

#20 [FEATURE] 공룡 테이블 조회 API
  src/main/java/kr/sesac/aoao/server/dino/controller/DinoController.java
  src/main/java/kr/sesac/aoao/server/dino/controller/dto/GetUserDinoResponse.java
  src/main/java/kr/sesac/aoao/server/dino/domain/Dino.java
  src/main/java/kr/sesac/aoao/server/dino/exception/DinoErrorCode.java
  src/main/java/kr/sesac/aoao/server/dino/repository/DinoEntity.java
  src/main/java/kr/sesac/aoao/server/dino/repository/DinoInfoEntity.java
  src/main/java/kr/sesac/aoao/server/dino/repository/DinoJpaRepository.java
  src/main/java/kr/sesac/aoao/server/dino/service/DinoService.java
  src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
  src/test/java/kr/sesac/aoao/server/dino/service/DinoServiceImplTest.java
Labels: 🐥 feat, ⚙️ chore

#24 [FEATURE] 투두리스트 폴더 생성 API 구현
  src/main/java/kr/sesac/aoao/server/dino/controller/DinoController.java
  src/main/java/kr/sesac/aoao/server/dino/repository/DinoJpaRepository.java
  src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
  src/main/java/kr/sesac/aoao/server/item/controller/dto/UseItemNumResponse.java
  src/main/java/kr/sesac/aoao/server/todo/config/InitializingPaletteConfig.java
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/request/TodoFolderSaveRequest.java
  src/main/java/kr/sesac/aoao/server/todo/domain/Palette.java
  src/main/java/kr/sesac/aoao/server/todo/exception/PaletteErrorCode.java
  src/main/java/kr/sesac/aoao/server/todo/exception/TodoErrorCode.java
  src/main/java/kr/sesac/aoao/server/todo/repository/PaletteEntity.java
  src/main/java/kr/sesac/aoao/server/todo/repository/PaletteJpaRepository.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderService.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImpl.java
  src/main/java/kr/sesac/aoao/server/user/exception/UserErrorCode.java
  src/main/resources/application.yml
  src/test/java/kr/sesac/aoao/server/dino/service/DinoServiceImplTest.java
  src/test/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImplTest.java
  src/test/java/kr/sesac/aoao/server/user/controller/UserControllerTest.java
Labels: 🐥 feat

#27 [FEATURE] 에러 처리 추가
  src/main/java/kr/sesac/aoao/server/global/exception/GlobalExceptionHandler.java
  src/test/java/kr/sesac/aoao/server/user/controller/UserControllerTest.java
Labels: 🐥 feat

#30 [FEATURE] 투두리스트 폴더 수정 및 삭제 API 구현
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/request/TodoFolderUpdateRequest.java
  src/main/java/kr/sesac/aoao/server/todo/exception/TodoFolderErrorCode.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderService.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImpl.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
Labels: 🐥 feat

#36 [FEATURE] 투두 항목 API 구현
  src/main/java/kr/sesac/aoao/server/global/config/SecurityConfig.java
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoController.java
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoQueryController.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/request/TodoSaveRequest.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/request/TodoUpdateRequest.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/FolderDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/FolderQueryDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/PaletteDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/PaletteQueryDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoFolderDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoQueryDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/exception/TodoErrorCode.java
  src/main/java/kr/sesac/aoao/server/todo/repository/PaletteEntity.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoEntity.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoJpaRepository.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderService.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImpl.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoQueryService.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoQueryServiceImpl.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoService.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoServiceImpl.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
Labels: 🐥 feat

#39 [FEATURE] 포인트 엔티티 생성
  src/main/java/kr/sesac/aoao/server/point/repository/PointEntity.java
  src/main/java/kr/sesac/aoao/server/point/repository/PointJpaRepository.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
Labels: 🐥 feat

#35 [FEAT] 다이어리 조회, 작성, 수정, 삭제 API 구현 초안
  settings.gradle
  src/main/java/kr/sesac/aoao/server/diary/controller/DiaryController.java
  src/main/java/kr/sesac/aoao/server/diary/controller/dto/request/DiaryCreateRequest.java
  src/main/java/kr/sesac/aoao/server/diary/controller/dto/request/DiaryUpdateRequest.java
  src/main/java/kr/sesac/aoao/server/diary/controller/dto/response/GetDiaryResponse.java
  src/main/java/kr/sesac/aoao/server/diary/domain/Diary.java
  src/main/java/kr/sesac/aoao/server/diary/exception/DiaryErrorCode.java
  src/main/java/kr/sesac/aoao/server/diary/repository/DiaryEntity.java
  src/main/java/kr/sesac/aoao/server/diary/repository/DiaryJpaRepository.java
  src/main/java/kr/sesac/aoao/server/diary/service/DiaryService.java
  src/main/java/kr/sesac/aoao/server/diary/service/DiaryServiceImpl.java
  src/test/java/kr/sesac/aoao/server/diary/service/DiaryServiceImplTest.java
Labels: 🐥 feat

#46 [BUG] rootProject 명 변경
  settings.gradle
Labels: 🐥 feat

#50 [BUG] 응답값이 없는 API 에 응답값 추가
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoController.java
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
Labels: 🛠️ bug

#51 Feat/29 create diary
  src/main/java/kr/sesac/aoao/server/diary/controller/DiaryController.java
  src/main/java/kr/sesac/aoao/server/dino/controller/dto/GetUserDinoResponse.java
  src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
Labels: ⭐️ refactor

#62 [BUG] 회원가입 관련 HTTP Method 변경
  src/main/java/kr/sesac/aoao/server/user/controller/UserController.java
Labels: 🛠️ bug, ⭐️ refactor

#68 [FEATURE] 마이페이지 API 구현
  build.gradle
  src/main/java/kr/sesac/aoao/server/global/support/S3Connector.java
  src/main/java/kr/sesac/aoao/server/global/support/S3Generator.java
  src/main/java/kr/sesac/aoao/server/global/support/S3Provider.java
  src/main/java/kr/sesac/aoao/server/global/support/StorageConnector.java
  src/main/java/kr/sesac/aoao/server/global/support/StorageGenerator.java
  src/main/java/kr/sesac/aoao/server/global/support/StorageProvider.java
  src/main/java/kr/sesac/aoao/server/global/support/dto/response/ResourceResponse.java
  src/main/java/kr/sesac/aoao/server/user/controller/UserCheckController.java
  src/main/java/kr/sesac/aoao/server/user/controller/UserController.java
  src/main/java/kr/sesac/aoao/server/user/controller/dto/request/UserNicknameUpdateRequest.java
  src/main/java/kr/sesac/aoao/server/user/controller/dto/request/UserPasswordUpdateRequest.java
  src/main/java/kr/sesac/aoao/server/user/controller/dto/response/UserProfileUpdateResponse.java
  src/main/java/kr/sesac/aoao/server/user/domain/User.java
  src/main/java/kr/sesac/aoao/server/user/repository/Resource.java
  src/main/java/kr/sesac/aoao/server/user/repository/ResourceRepository.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
  src/main/java/kr/sesac/aoao/server/user/repository/UserJpaRepository.java
  src/main/java/kr/sesac/aoao/server/user/service/UserService.java
  src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: 🐥 feat

#70 [BUG] 다이노 레벨 수정 및 배포 스크립트 수정
  scripts/deploy.sh
  src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
Labels: 🛠️ bug

#72 [CHORE] 유저 아이템 생성 코드 수정
  scripts/deploy.sh
  src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
Labels: ⚙️ chore

#74 [BUG] 유저 아이템 추가
  src/main/java/kr/sesac/aoao/server/item/repository/ItemJpaRepository.java
  src/main/java/kr/sesac/aoao/server/item/repository/UserItemEntity.java
  src/main/java/kr/sesac/aoao/server/item/repository/UserItemJpaRepository.java
  src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
Labels: 🛠️ bug

#78 [FEATURE] 투두리스트 폴더 색상 추가
  src/main/java/kr/sesac/aoao/server/todo/domain/Palette.java
Labels: ⭐️ refactor

#81 [BUG] 다이어리 API 수정
  src/main/java/kr/sesac/aoao/server/diary/controller/dto/response/GetDiaryResponse.java
  src/main/java/kr/sesac/aoao/server/diary/exception/DiaryErrorCode.java
  src/main/java/kr/sesac/aoao/server/diary/repository/DiaryEntity.java
  src/main/java/kr/sesac/aoao/server/diary/repository/DiaryJpaRepository.java
  src/main/java/kr/sesac/aoao/server/diary/service/DiaryServiceImpl.java
Labels: 🛠️ bug, ⭐️ refactor

#83 [BUG] 팔레트가 계속해서 저장되는 문제 해결
  src/main/java/kr/sesac/aoao/server/todo/config/InitializingPaletteConfig.java
Labels: 🛠️ bug

#85 [BUG] 전반적인 API 개선
  src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoController.java
  src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/FolderDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/FolderSaveResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoFolderDetailResponse.java
  src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoSaveResponse.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoService.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoServiceImpl.java
  src/main/java/kr/sesac/aoao/server/user/controller/dto/response/MyPageResponse.java
  src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
Labels: ⭐️ refactor

#93 [FEATURE] 투두리스트 및 폴더 관련 주석 추가
  src/main/java/kr/sesac/aoao/server/todo/domain/Palette.java
  src/main/java/kr/sesac/aoao/server/todo/exception/PaletteErrorCode.java
  src/main/java/kr/sesac/aoao/server/todo/exception/TodoErrorCode.java
  src/main/java/kr/sesac/aoao/server/todo/exception/TodoFolderErrorCode.java
  src/main/java/kr/sesac/aoao/server/todo/repository/PaletteEntity.java
  src/main/java/kr/sesac/aoao/server/todo/repository/PaletteJpaRepository.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoEntity.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
  src/main/java/kr/sesac/aoao/server/todo/repository/TodoJpaRepository.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderService.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoQueryService.java
  src/main/java/kr/sesac/aoao/server/todo/service/TodoService.java
Labels: ⭐️ refactor

#94 [CHORE] 주석 추가 및 사용하지 않는 코드 제거
  src/main/java/kr/sesac/aoao/server/dino/domain/Dino.java
  src/main/java/kr/sesac/aoao/server/dino/exception/DinoErrorCode.java
  src/main/java/kr/sesac/aoao/server/dino/repository/DinoEntity.java
  src/main/java/kr/sesac/aoao/server/dino/repository/DinoInfoEntity.java
  src/main/java/kr/sesac/aoao/server/dino/repository/DinoInfoJpaRepository.java
  src/main/java/kr/sesac/aoao/server/dino/repository/DinoJpaRepository.java
  src/main/java/kr/sesac/aoao/server/dino/service/DinoService.java
  src/main/java/kr/sesac/aoao/server/item/domain/Item.java
  src/main/java/kr/sesac/aoao/server/item/exception/ItemErrorCode.java
  src/main/java/kr/sesac/aoao/server/item/repository/ItemEntity.java
  src/main/java/kr/sesac/aoao/server/item/repository/ItemJpaRepository.java
  src/main/java/kr/sesac/aoao/server/item/repository/UserItemEntity.java
  src/main/java/kr/sesac/aoao/server/item/repository/UserItemJpaRepository.java
  src/main/java/kr/sesac/aoao/server/item/service/ItemService.java
  src/main/java/kr/sesac/aoao/server/item/service/ItemServiceImpl.java
  src/test/java/kr/sesac/aoao/server/ServerApplicationTests.java
  src/test/java/kr/sesac/aoao/server/diary/service/DiaryServiceImplTest.java
  src/test/java/kr/sesac/aoao/server/dino/service/DinoServiceImplTest.java
  src/test/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImplTest.java
  src/test/java/kr/sesac/aoao/server/user/controller/UserControllerTest.java
  src/test/java/kr/sesac/aoao/server/user/service/UserServiceImplTest.java
Labels: ⚙️ chore, ⭐️ refactor
